### ISSUE TITLE
Readme and CoffeeServiceTests differ in cream required for Cappuccino.

### ISSUE THREAD

**Issue by cameronhudson8** [mbhave/coffee-machine#3]
The readme says that 2 units of cream are required for a cappuccino:

> | 	Drink       | 	Ingredients										| Cost  |
> | ------------- | ------------------------------------------------- | ----- |
> | coffee      	| coffee (2 units), sugar (1 unit)				 	| $2.75 |
> | cappuccino  	| coffee (2 units), sugar (1 unit), cream (2 units) | $2.90 |
> | caffe mocha 	| coffee (1 unit), sugar (1 unit), cream (1 unit) 	| $3.90 |

However, `CoffeeServiceTests` requires that only 1 unit of cream be deducted:

	@Test
	public void makeDrink() {
		this.machine.makeDrink("cappuccino");
		verify(this.inventory).deduct("coffee", 2);
		verify(this.inventory).deduct("sugar", 1);
		verify(this.inventory).deduct("cream", 1);
	}

**Comment by mbhave** [comment]
Thanks, I've update the README to match the tests.
